// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlT622tB8D4_AdaM3mYVoTz8XW8MrMznI',
    appId: '1:801627551806:web:5b962723fe3adffa32396f',
    messagingSenderId: '801627551806',
    projectId: 'ase456project',
    authDomain: 'ase456project.firebaseapp.com',
    storageBucket: 'ase456project.appspot.com',
    measurementId: 'G-QX6R0L3XYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhaCpznhLI5Of7PZObFuplO1IVV2wgEk',
    appId: '1:801627551806:android:e616c7e17dae4a8132396f',
    messagingSenderId: '801627551806',
    projectId: 'ase456project',
    storageBucket: 'ase456project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6a7DofouD-z5IFPxs9AI86izwPo64Ag',
    appId: '1:801627551806:ios:53be09491cac640c32396f',
    messagingSenderId: '801627551806',
    projectId: 'ase456project',
    storageBucket: 'ase456project.appspot.com',
    iosClientId: '801627551806-nfarggiq3rogr3sq0fhfkhr1n2fmb06a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ase456PersonalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN6a7DofouD-z5IFPxs9AI86izwPo64Ag',
    appId: '1:801627551806:ios:53be09491cac640c32396f',
    messagingSenderId: '801627551806',
    projectId: 'ase456project',
    storageBucket: 'ase456project.appspot.com',
    iosClientId: '801627551806-nfarggiq3rogr3sq0fhfkhr1n2fmb06a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ase456PersonalProject',
  );
}
